name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4      
      - name: npx cypress run --spec cypress/e2e/sequenced-tests.cy.js
        uses: cypress-io/github-action@v6